alfresco-content-services:
  repository:
    replicaCount: 1
    # This assumes you have a custom ACS Repo image in your local machine
    image:
      repository: alfresco-content-services-zia-custom
      tag: development
      pullPolicy: Never # Required - This image is only available locally

  transformrouter:
    replicaCount: 1

  pdfrenderer:
    replicaCount: 1

  imagemagick:
    replicaCount: 1

  libreoffice:
    replicaCount: 1

  tika:
    replicaCount: 1

  transformmisc:
    replicaCount: 1

  aiTransformer:
    replicaCount: 1

  filestore:
    replicaCount: 1

  share:
    replicaCount: 1
    # This assumes you have a custom ACS Share image in your local machine
    image:
      repository: alfresco-share-zia-custom
      tag: development
      pullPolicy: Never # Required - This image is only available locally

  database:
    external: true
    driver: "org.mariadb.jdbc.Driver"
    user: alfresco
    password: alfresco
    url: "'jdbc:mariadb://192.168.27.111:3306/alfresco?useUnicode=yes&characterEncoding=UTF-8'"

  postgresql:
    enabled: false
    replicaCount: 1

  alfresco-infrastructure:
    persistence:
      enabled: false

  alfresco-search:
    persistence:
      enabled: false

  externalProtocol: http
  externalHost: 127.0.0.1
  externalPort: 80
